apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meter.secretName" . }}
  labels:
    {{- include "meter.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-user: {{ .Values.credentials.postgresUser | quote }}
  postgres-password: {{ .Values.credentials.postgresPassword | quote }}
  postgres-database: {{ .Values.credentials.postgresDatabase | quote }}
  clickhouse-user: {{ .Values.credentials.clickhouseUser | quote }}
  clickhouse-password: {{ .Values.credentials.clickhousePassword | quote }}
  clickhouse-database: {{ .Values.credentials.clickhouseDatabase | quote }}
  database-url: {{ include "meter.databaseUrl" . | quote }}
  control-plane-database-url: {{ include "meter.controlPlaneDatabaseUrl" . | quote }}
  dashboard-password: {{ .Values.dashboard.password | quote }}
  dashboard-session-secret: {{ .Values.dashboard.sessionSecret | quote }}
