apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meter.secretName" . }}
  labels:
    {{- include "meter.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-user: {{ .Values.credentials.postgresUser | quote }}
  postgres-password: {{ .Values.credentials.postgresPassword | quote }}
  postgres-database: {{ .Values.credentials.postgresDatabase | quote }}
  database-url: {{ include "meter.databaseUrl" . | quote }}
  control-plane-database-url: {{ include "meter.controlPlaneDatabaseUrl" . | quote }}
